export const MAIN_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const NOTFOUND_ROUTE = '/notfound'
export const REQUEST_ROUTE = '/request/:page'
export const REQUEST_PROCESSING_ROUTE = '/request/processing'
export const REQUEST_PROCESSED_ROUTE = '/request/processed'
export const SALES_ROUTE = '/sales/:page/:id?'
export const SALES_REQUEST_FORM_ROUTE = '/sales/requestForm'
export const SALES_HISTORY_ROUTE = '/sales/history'

export const MIXERS_ROUTE = '/mixers/:page'
export const MIXERS_PASTRY_ROUTE = '/mixers/pastry'
export const MIXERS_BAKINGPRODUCTS_ROUTE = '/mixers/bakingProducts'
export const MIXERS_REMAIN_RAW_MATERIALS_ROUTE = '/mixers/remainRawMaterials'
export const MIXERS_REMAIN_PRODUCTS_ROUTE = '/mixers/remainProducts'
export const MIXERS_SHIFT_ACCOUNTING_ROUTE = '/mixers/shiftAccounting'

export const RELEASE_ROUTE = '/release/:page'
export const RELEASE_DISTRIBUTION_ROUTE = '/release/distribution'
export const RELEASE_REFUND_ROUTE = '/release/refund'

//Admin routes
export const ADMIN_ROUTE = '/admin/:page'
export const ADMIN_PRODUCTS_ROUTE = '/admin/products'
export const ADMIN_USERS_ROUTE = '/admin/users'
export const ADMIN_RELEASE_ROUTE = '/admin/releases'
export const ADMIN_UNIQUEPRICE_ROUTE = '/admin/uniquePrice'
export const ADMIN_PROVIDER_ROUTE = '/admin/provider'
export const ADMIN_GOODS_ROUTE = '/admin/goods'
export const ADMIN_GOOD_CATEGORIES_ROUTE = '/admin/goodCategories'
export const ADMIN_MAGAZINES_ROUTE = '/admin/magazines'
export const ADMIN_OVERPRICE_ROUTE = '/admin/overprice'
export const ADMIN_DEPART_PERSONAL_ROUTE = '/admin/departPersonal'

export const FINANCE_ROUTE = '/finance/:page'
export const FINANCE_INPUT_ROUTE = '/finance/input'
export const FINANCE_HISTORY_ROUTE = '/finance/history'
export const FINANCE_REPORT_ROUTE = '/finance/report'

export const PURCHASE_ROUTE = '/purchase/:page'
export const PURCHASE_PRODUCTS_ROUTE = '/purchase/products'
export const PURCHASE_DEBT_ROUTE = '/purchase/debt'

export const INVENTORY_ROUTE = '/inventory/:page'
export const INVENTORY_FACT_ROUTE = '/inventory/fact'
export const INVENTORY_DETAILS_ROUTE = '/inventory/details'
export const INVENTORY_HISTORY_ROUTE = '/inventory/history'

export const SELLS_ROUTE = '/sells/:page'
export const SELLS_JOURNAL_ROUTE = '/sells/journal'
export const SELLS_INVOICE_ROUTE = '/sells/invoice'
export const SELLS_DEBT_ACCOUNTING_ROUTE = '/sells/debtAccounting'
export const SELLS_DEBT_TRANSFER_ROUTE = '/sells/debtTransfer'

export const REPORT_ROUTE = '/reports/:page'
export const BREAD_REPORT_ROUTE = '/reports/breadView'
export const RELEASE_REPORT_ROUTE = '/reports/releaseView'
export const VISIT_REPORT_ROUTE = '/reports/visitView'
export const RECONCILIATION_REPORT_ROUTE = '/reports/reconciliationView'
